[build]
  publish = "dist"
  command = "npm install --include=optional sharp && npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
